<?php

namespace Aura\Base\Tests;

use Aura\Base\AuraServiceProvider;
use Aura\Base\Providers\AuthServiceProvider;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Foundation\Testing\Concerns\InteractsWithViews;
use Illuminate\Foundation\Testing\LazilyRefreshDatabase;
use Intervention\Image\ImageServiceProvider;
use Lab404\Impersonate\ImpersonateServiceProvider;
use Laravel\Fortify\FortifyServiceProvider;
use Livewire\LivewireServiceProvider;
use Orchestra\Testbench\Concerns\WithWorkbench;
use Orchestra\Testbench\TestCase as Orchestra;
use ReflectionObject;
use Spatie\LaravelRay\RayServiceProvider;

class TestCase extends Orchestra
{
    use InteractsWithViews;
    use LazilyRefreshDatabase;

    // use WithWorkbench;

    protected function setUp(): void
    {
        parent::setUp();

        $this->withoutVite();

        // Mock file uploads are handled by the mock file in tests/Mocks/
        // Laravel's real-time facade system will automatically use the mock class

        // Add this before the Factory setup
        config()->set('app.env', 'testing');
        config()->set('filesystems.default', 'local');

        Factory::guessFactoryNamesUsing(
            fn (string $modelName) => 'Aura\\Base\\Database\\Factories\\'.class_basename($modelName).'Factory'
        );
    }

    /**
     * Isolate the application skeleton per parallel worker.
     *
     * Under `pest --parallel` every worker boots from the same testbench
     * skeleton, so tests that write into it race each other across processes:
     *
     *  - database/migrations: generated migration files are scanned by every
     *    worker's RefreshDatabase, so one worker can require a file another
     *    worker is mid-create/delete on (random FileNotFoundException).
     *  - app/Aura/{Resources,Fields,Widgets}: the generator commands write
     *    here and Aura::getAppResources() scans it on every boot, so one
     *    worker's cleanup deletes the directory while another worker's Finder
     *    iterates it (random DirectoryNotFoundException), or a worker registers
     *    a half-written resource generated by a different worker.
     *  - public/vendor, routes/, plugins/, composer.json, and the compiled
     *    views in storage/framework/views are likewise shared and mutated.
     *
     * Each worker therefore gets its own throwaway copy of the whole skeleton
     * in the system temp directory. Narrower fixes (useAppPath/usePublicPath)
     * do not work: Application::getNamespace() resolves the app path against
     * composer.json's psr-4 map and throws once the app path leaves the
     * skeleton. Serial runs (no worker token) keep the shared skeleton.
     *
     * UNIQUE_TEST_TOKEN is preferred over TEST_TOKEN: TEST_TOKEN is just the
     * worker number (1..N), so its directories would be reused by every later
     * run and accumulate stale state; UNIQUE_TEST_TOKEN changes per run.
     */
    public static function applicationBasePath()
    {
        $token = getenv('UNIQUE_TEST_TOKEN') ?: getenv('TEST_TOKEN');

        if (! $token) {
            return parent::applicationBasePath();
        }

        $source = parent::applicationBasePath();
        $target = sys_get_temp_dir().'/aura-test-skeleton-'.$token;

        if (! is_dir($target)) {
            static::copySkeleton($source, $target);
        }

        return $target;
    }

    public function getEnvironmentSetUp($app)
    {
        config()->set('database.default', 'testing');

        // Add these lines
        config()->set('app.env', 'testing');
        config()->set('livewire.temporary_file_upload.disk', 'local');

        // load the aura config
        // config()->set('aura', require __DIR__.'/../config/aura.php');

        // without exception handling
        // $this->withoutExceptionHandling();

        $migration = require __DIR__.'/../database/migrations/create_aura_tables.php.stub';
        $migration->up();
    }

    /**
     * Copy the testbench skeleton, skipping symlinks (the vendor symlink is
     * recreated inside the copy by testbench's CreateVendorSymlink bootstrap).
     */
    protected static function copySkeleton(string $source, string $target): void
    {
        $files = new \RecursiveDirectoryIterator($source, \FilesystemIterator::SKIP_DOTS);
        $withoutSymlinks = new \RecursiveCallbackFilterIterator($files, fn (\SplFileInfo $file) => ! $file->isLink());
        $iterator = new \RecursiveIteratorIterator($withoutSymlinks, \RecursiveIteratorIterator::SELF_FIRST);

        mkdir($target, 0777, true);

        foreach ($iterator as $file) {
            $destination = $target.'/'.$iterator->getSubPathname();

            $file->isDir() ? mkdir($destination, 0777) : copy($file->getPathname(), $destination);
        }
    }

    protected function defineEnvironment($app)
    {
        // Prevent actual file upload handling
        $app['config']->set('livewire.temporary_file_upload.disk', 'local');
        $app['config']->set('livewire.temporary_file_upload.middleware', null);

    }

    // protected function tearDown(): void
    // {
    //     $refl = new ReflectionObject($this);
    //     foreach ($refl->getProperties() as $prop) {
    //         if (!$prop->isStatic() && 0 !== strpos($prop->getDeclaringClass()->getName(), 'PHPUnit_')) {
    //             $prop->setAccessible(true);
    //             $prop->setValue($this, null);
    //         }
    //     }

    //     parent::tearDown();

    // }

    protected function getPackageProviders($app)
    {
        // Disable file uploads in Livewire before loading the provider
        $app['config']->set('livewire.temporary_file_upload.directory', null);
        $app['config']->set('livewire.temporary_file_upload.middleware', null);
        $app['config']->set('livewire.temporary_file_upload.upload_url', null);
        $app['config']->set('livewire.temporary_file_upload.rules', null);

        return [
            LivewireServiceProvider::class,
            FortifyServiceProvider::class,
            AuthServiceProvider::class,
            AuraServiceProvider::class,
            ImpersonateServiceProvider::class,
            RayServiceProvider::class,
            ImageServiceProvider::class,
        ];
    }
}
