<?php

use Aura\Base\Fields\AdvancedSelect;

// Generated by Copilot Chat but not correct yet

// it('can get the correct options', function () {
//     $model = \Mockery::mock('Model');
//     $model->shouldReceive('get')->andReturn(collect([
//         (object) ['id' => 1, 'title' => 'Option 1'],
//         (object) ['id' => 2, 'title' => 'Option 2'],
//     ]));

//     $field = new AdvancedSelect($model);
//     $options = $field->get('id', 'title');

//     expect($options)->toBeArray();
//     expect($options)->toContain([
//         'value' => 1,
//         'label' => 'Option 1',
//     ]);
//     expect($options)->toContain([
//         'value' => 2,
//         'label' => 'Option 2',
//     ]);
// });

// it('can get the correct values', function () {
//     $model = \Mockery::mock('Model');
//     $model->shouldReceive('get')->andReturn(collect([
//         (object) ['id' => 1, 'title' => 'Option 1'],
//         (object) ['id' => 2, 'title' => 'Option 2'],
//     ]));

//     $field = new AdvancedSelect($model);
//     $values = $field->values($model);

//     expect($values)->toBeArray();
//     expect($values)->toContain([
//         'id' => 1,
//         'title' => 'Option 1',
//     ]);
//     expect($values)->toContain([
//         'id' => 2,
//         'title' => 'Option 2',
//     ]);
// });
