name: static-analysis

on:
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - '**.php'
      - 'composer.*'
      - 'phpstan*.neon*'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - uses: ramsey/composer-install@v4

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G --error-format=github --no-progress
